/**
 * DRIFT GUARD for the compile beat, rewritten 2026-09-25 alongside Guard.tsx.
 *
 * Guard.tsx retypes numbers from __fixtures__/trailofbits-skills.json (a REAL
 * `vigiles audit` run against test/dogfood/trailofbits-skills-curated@6d05be4,
 * plus a REAL `vigiles compile` + `vigiles audit` run against
 * scripts/dogfood/solidity-audit-demo), generated by
 * scripts/gen-trailofbits-expected.mjs in `pretest:browser`. If this fails,
 * either the vendored marketplace slice moved or the demo spec's compiled
 * output changed — fix Guard.tsx (or the fixture's source data), never this
 * test.
 *
 * The OLD version of this file asserted BATTERY_ROWS (the hooks battery,
 * 2 of 7 vs 7 of 7) — that export no longer exists; Guard.tsx's own header
 * comment explains why and where that content now lives
 * (HooksExperimental.tsx). See git history for the old assertions.
 */
import { describe, it, expect } from "vitest";
import trailofbits from "./__fixtures__/trailofbits-skills.json";

describe("the Guard section quotes the real trailofbits/skills-curated audit", () => {
  it("scv-scan's allowed-tools list matches the fixture, not a retyped guess", () => {
    expect(trailofbits.scvScan.allowedTools).toEqual(["Read", "Grep", "Glob"]);
  });

  it("scv-scan holds no fence — the whole headline claim", () => {
    expect(trailofbits.scvScan.fence).toBe("none");
  });

  it("the headline ratio (N of M unfenced) is internally consistent", () => {
    // Guard.tsx renders `{noFence} of {trifectaApplicable}` — both halves come
    // from the same fixture, so this pins that noFence never exceeds the
    // applicable count (a malformed slice could otherwise silently invert it).
    expect(trailofbits.noFence).toBeLessThanOrEqual(
      trailofbits.trifectaApplicable,
    );
    expect(trailofbits.noFence).toBeGreaterThan(0);
  });

  it("the compiled demo actually declares disallowed-tools", () => {
    expect(trailofbits.demo.compiled).toContain(
      "disallowed-tools: [Bash, WebFetch, WebSearch]",
    );
  });

  it("the compiled demo scores Safety 100 — the fix half of the claim", () => {
    // Guard.tsx prints this number as proof compiling with disallowedTools
    // actually clears the finding, not just that the field exists in the
    // schema. The generator itself asserts this before writing the fixture
    // (fails the build on a compiler regression); this pins the RENDERED copy
    // to the same number.
    expect(trailofbits.demo.safetyScore).toBe(100);
  });

  it("the live exfiltration attempt went through unfenced and was denied fenced", () => {
    // Added 2026-09-26 (Ernie: "still weak, find a stronger case") — a REAL
    // runHarnessTest attack, not a static score. Both directions asserted by
    // the generator itself before it writes the fixture; this pins the
    // rendered copy to the same two booleans, so a regression in either
    // direction fails a browser test a human actually reads, not just a
    // build-time throw three files away.
    expect(trailofbits.demo.exfil.vulnerableWentThrough).toBe(true);
    expect(trailofbits.demo.exfil.fencedDenied).toBe(true);
    expect(trailofbits.demo.exfil.fencedDenialMessage).toBe(
      "Permission to use Bash has been denied.",
    );
  });
});
