import { CodeBlock } from "@/components/CodeBlock";
import SKILL_TEST from "@/snippets/skill-test.ts?raw";
import trailofbits from "./__fixtures__/trailofbits-skills.json";
import lock from "./__fixtures__/tdd-trigger-rate.json";

/**
 * TEST and EVAL — the two beats `audit` cannot play.
 *
 * WHY IT EXISTS. The landing led with `audit` (a graded read) and named the other
 * three verbs once each in a map. A visitor came away thinking vigiles is a linter.
 * The founder, 2026-09-09: "audit is a starting point and then people going through
 * the website should think wow this stuff like testing and evals really solves my
 * problem."
 *
 * 🔴 REWRITTEN 2026-09-25 (Ernie): this beat was about a HOOK (davila7's
 * force-push guard) — the same story `compile` (Guard.tsx) told, one screen up.
 * Ernie: hooks don't scare people much, partly because of Claude Code's
 * auto-mode; skills are the thing most authors actually ship and the thing most
 * visitors will recognise. The old content is commented out below rather than
 * deleted — see "OLD CONTENT" — and now lives, shrunk, in the small hooks
 * section (`HooksExperimental.tsx`) this rewrite added after `compile`.
 *
 * THE ARGUMENT, and why it is NOT on the Hero's repo. The Hero demo grades
 * davila7/claude-code-templates; the original `test`/`compile` copy stayed on
 * that repo on purpose, to avoid a hypothetical. `eval` already broke that
 * rule once (it measures "a popular open-source TDD skill", a third repo) —
 * so staying on ONE repo throughout was already not this page's actual
 * invariant; not introducing a HYPOTHETICAL is. trailofbits/skills-curated is
 * Trail of Bits' own actively-reviewed Claude Code skill marketplace: a
 * contribution guide that tells authors to write `allowed-tools:`, a
 * `/review-plugin` command run on every import — the least hypothetical
 * "widely-copied pattern" available for a claim about SKILLS, because if a
 * security company's own reviewed marketplace has the gap, "just write it
 * more carefully" is not the fix. Full provenance:
 * test/dogfood/trailofbits-skills-curated@6d05be4/SOURCE.
 *
 * 🔴 THE COPY STANDARD FOR THIS SECTION AND ANY LIKE IT (Ernie, 2026-09-09).
 * A reader must look at the code and instantly think "wait — yeah, I have seen
 * this." Write the BUG they have already lived through, not the mechanism we
 * built. "A hook is a process, pipe it an event" describes plumbing; "the guard
 * you think protects you runs nothing" is the thing that happened to them.
 * Every beat should name a concrete failure a plugin author recognises: a guard
 * that looks unconditional and only ever fires on one command; a tool that is
 * silently dropped; a skill that never fires because a sibling took the prompt.
 * If a paragraph would still read fine in a competitor's docs, it is describing
 * a feature and has not earned its place — rewrite it as the failure.
 *
 * EVERY NUMBER IS PINNED. The counts come from
 * __fixtures__/trailofbits-skills.json, regenerated by
 * scripts/gen-trailofbits-expected.mjs in `pretest:browser` — a REAL `vigiles
 * test` run against the vendored slice, not a retyped guess — and asserted by
 * Measure.browser.test.tsx: a retyped number is one that drifts, and this
 * section's whole claim is that it does not need a footnote.
 */

/**
 * The snippet is a REAL FILE the type-checker compiles (`npm run check` runs
 * `tsc --noEmit -p site/tsconfig.json`), imported here as text. A hand-typed string
 * is not checked by anything: the eval snippet shipped naming two exports that do
 * not exist — `defineEval` and `skillResolved` from "vigiles/eval" — with build,
 * lint, prettier, browser and e2e all green. Now a renamed export fails the build
 * with "Did you mean 'runHook'?" instead of reaching a reader.
 *
 * MEASURED LIMIT, so nobody over-trusts this: tsc catches the wrong NAME, and
 * catches wrong types only where the API is precisely typed. `tool: 123` currently
 * passes, because runHook's options type is loose there.
 */

/**
 * BEAT: test. Split out of a single `Measure` component on 2026-09-09 so the
 * `compile` beat (Guard) can sit between test and eval — the page is ordered
 * test · compile · eval, which is the order a reader meets the failures, not
 * the order the sections were written.
 */
export function MeasureTest() {
  return (
    <>
      <section id="test" className="scroll-mt-8 border-t border-border/60">
        <div className="mx-auto w-full max-w-4xl px-6 py-20 sm:py-24">
          <p className="font-mono text-xs text-primary">
            $ vigiles test · no model · free in CI
          </p>
          <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
            {trailofbits.surfaces} skills, reviewed by a security company.{" "}
            <span className="whitespace-nowrap">Zero are tested.</span>
          </h2>
          <p className="mt-4 max-w-2xl text-lg leading-relaxed text-muted-foreground">
            Trail of Bits runs a curated Claude Code marketplace — a
            contribution guide, a review command, {trailofbits.plugins} plugins.
            Nothing enforces a test, because nothing can read &ldquo;did anyone
            write one&rdquo; off a description.
          </p>

          <div className="mt-8 rounded-xl border border-border/60 bg-card/30 p-5">
            <p className="font-mono text-xs text-muted-foreground">
              $ {trailofbits.testCommand}
            </p>
            <p className="mt-3 whitespace-pre-wrap break-words font-mono text-sm text-foreground">
              {trailofbits.testOutput}
            </p>
          </div>

          <p className="mt-6 max-w-2xl text-sm leading-relaxed text-muted-foreground">
            Every one of the{" "}
            <strong className="text-foreground">
              {trailofbits.surfaces} skills and agents
            </strong>{" "}
            in the marketplace — including{" "}
            <code className="font-mono">scv-scan</code>, a Solidity
            vulnerability auditor — ships without a colocated harness or eval
            file anywhere in the repo. <code className="font-mono">ls</code>{" "}
            answers &ldquo;is this tested&rdquo; without running anything; here
            the answer is no, for all {trailofbits.surfaces}.
          </p>

          <CodeBlock code={SKILL_TEST} language="tsx" className="mt-8" />
          <p className="mt-3 text-sm text-muted-foreground">
            The test lives next to the thing it tests —{" "}
            <code className="font-mono text-xs">SKILL.md</code> gets{" "}
            <code className="font-mono text-xs">&lt;name&gt;.harness.mjs</code>.
            One property earns that:{" "}
            <code className="font-mono text-xs">ls</code> answers &ldquo;is this
            tested?&rdquo; without running anything.
          </p>

          {/* Collapsed on purpose. A reader who has never had a test push to their
              real remote does not need this; the one who has, opens it. */}
          <details className="group mt-6 rounded-xl border border-border/60 bg-card/30 px-5">
            <summary className="cursor-pointer list-none py-4 text-base font-medium text-foreground">
              But my skill actually does things — what stops the test doing them
              for real?
            </summary>
            <div className="space-y-4 pb-5 text-sm leading-relaxed text-muted-foreground">
              <p className="text-foreground">
                You can throw away a temp directory. You cannot un-push a branch
                or un-charge an API call.
              </p>
              <p>
                <strong className="text-foreground">
                  Every run is disposable.
                </strong>{" "}
                Each test gets a fresh throwaway working directory, so a skill
                that writes files leaves nothing behind.
              </p>
              <p>
                <strong className="text-foreground">
                  Effects you cannot take back get intercepted, not contained.
                </strong>{" "}
                A tool call can be caught and asserted on without being allowed
                to happen — you check that the agent <em>tried</em> to push,
                while no push occurs.
              </p>
              <p>
                <strong className="text-foreground">
                  Somebody else&rsquo;s skill runs confined.
                </strong>{" "}
                Code you did not write executes with no network, a read-only
                filesystem and a cleared environment. That wall is Linux
                (bubblewrap); where the kernel features are absent vigiles
                refuses to run foreign code rather than quietly running it
                unconfined.
              </p>
            </div>
          </details>
        </div>
      </section>
    </>
  );
}

// ============================================================================
// OLD CONTENT (pre-2026-09-25) — commented out, not deleted, per house rule
// ("дописывать, не переписывать"). This told the SAME story `compile`
// (Guard.tsx) told one screen up, about davila7's force-push guard. Replaced
// by the skill-focused beat above; the hook material now lives, shrunk, in
// HooksExperimental.tsx. If this is ever restored, regenerate
// __fixtures__/davila7-guard.json first (scripts/gen-davila7-expected.mjs is
// unchanged and still runs in `pretest:browser`).
// ============================================================================
//
// function Verdict({ row }: { row: (typeof fixture.rows)[number] }) {
//   return (
//     <div className="flex flex-col gap-1 border-t border-border/60 py-4 sm:flex-row sm:items-baseline sm:justify-between sm:gap-6">
//       <code className="whitespace-pre-wrap break-words font-mono text-sm text-foreground">
//         {row.command}
//       </code>
//       <span
//         className={`shrink-0 font-mono text-xs ${
//           row.blocked ? "text-good" : "text-muted-foreground"
//         }`}
//       >
//         {row.blocked ? "blocked" : "not run"}
//       </span>
//     </div>
//   );
// }
//
// export function MeasureTest_HOOKS_VERSION() {
//   const { rows, spellings } = fixture;
//   return (
//     <section id="test" className="scroll-mt-8 border-t border-border/60">
//       <div className="mx-auto w-full max-w-4xl px-6 py-20 sm:py-24">
//         <p className="font-mono text-xs text-primary">
//           $ vigiles test · no model · free in CI
//         </p>
//         <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
//           You have a safety hook. What does it actually stop?
//         </h2>
//         <p className="mt-4 max-w-2xl text-lg leading-relaxed text-muted-foreground">
//           The repo you just watched get graded ships one. It looks like a
//           blanket deny — and for two of these three commands, Claude Code
//           never even calls it.
//         </p>
//         <div className="mt-8">
//           {rows.map((r) => (
//             <Verdict key={r.id} row={r} />
//           ))}
//         </div>
//         <p className="mt-6 max-w-2xl text-sm leading-relaxed text-muted-foreground">
//           Its hook command is a bare <code className="font-mono">echo</code>{" "}
//           of a deny decision, so a checker that just pipes commands through it
//           would certify it as stopping all three. It does not — Claude Code
//           only ever invokes it for a force push. vigiles reports what the
//           guard was actually asked, and refuses the false green.
//         </p>
//         <p className="mt-4 max-w-2xl text-sm leading-relaxed text-muted-foreground">
//           And it does not manufacture a complaint either: fed{" "}
//           <strong className="text-foreground">
//             {spellings.fed} shell re-spellings
//           </strong>{" "}
//           of a force push — quoted flags, <code className="font-mono">sudo</code>,
//           tabs, escapes — this guard blocked{" "}
//           <strong className="text-foreground">all {spellings.blocked}</strong>.
//         </p>
//       </div>
//     </section>
//   );
// }

/** BEAT: eval — the one tier that needs a real model. */
export function MeasureEval() {
  // Only the prompts that did NOT reliably fire — the eight that always fire are
  // not the story, and listing all ten is the rule-dump shape we already cut once.
  const misses = lock.report.perPrompt.filter((p) => p.rate < 1);
  return (
    <>
      <section id="eval" className="scroll-mt-8 border-t border-border/60">
        <div className="mx-auto w-full max-w-4xl px-6 py-20 sm:py-24">
          <p className="font-mono text-xs text-primary">
            $ vigiles eval · real model · your Claude subscription
          </p>
          <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
            Your skill has a description. Does it fire?
          </h2>
          <p className="mt-4 max-w-2xl text-lg leading-relaxed text-muted-foreground">
            We measured a popular open-source TDD skill against ten ways of
            asking for test-first work. Eight reached it. These two did not:
          </p>

          <div className="mt-8 overflow-hidden rounded-xl border border-border/60">
            {misses.map((m) => (
              <div
                key={m.prompt}
                className="flex flex-col gap-1 border-b border-border/60 bg-card/40 p-5 sm:flex-row sm:items-baseline sm:justify-between sm:gap-6"
              >
                <p className="whitespace-pre-wrap break-words font-mono text-sm text-foreground">
                  {m.prompt}
                </p>
                <span className="shrink-0 font-mono text-xs text-muted-foreground">
                  fired {m.fired} of {m.trials}
                </span>
              </div>
            ))}
            <div className="bg-card/20 p-5">
              <p className="text-sm leading-relaxed text-muted-foreground">
                Every prompt it <em>did</em> fire on asks for something new.
                Both of these ask for tests around code that already exists —
                which is most of the work most people do.
              </p>
            </div>
          </div>

          <p className="mt-6 max-w-2xl text-sm leading-relaxed text-muted-foreground">
            {Math.round(lock.report.rate * 100)}% over {lock.report.n} runs (
            {lock.report.perPrompt.length} prompts x{" "}
            {lock.report.perPrompt[0].trials} trials, {lock.model}, measured{" "}
            {lock.builtAt.slice(0, 10)}). Run it against your own skill and you
            get the same shape of answer: which phrasings reach it, and which
            quietly do not. Billed to the Claude subscription you already pay
            for, not a metered key.
          </p>
        </div>
      </section>
    </>
  );
}
