import { CodeBlock } from "@/components/CodeBlock";
import RUN_HOOK from "@/snippets/hook-test.ts?raw";
import fixture from "./__fixtures__/davila7-guard.json";

/**
 * TEST and EVAL — the two beats `audit` cannot play.
 *
 * WHY IT EXISTS. The landing led with `audit` (a graded read) and named the other
 * three verbs once each in a map. A visitor came away thinking vigiles is a linter.
 * The founder, 2026-09-09: "audit is a starting point and then people going through
 * the website should think wow this stuff like testing and evals really solves my
 * problem."
 *
 * THE ARGUMENT, and why it is on THIS repo. The demo above grades
 * davila7/claude-code-templates. So these sections stay on the same repo the reader
 * just watched get graded, instead of introducing a hypothetical. Its force-push
 * guard is a real, MIT, SHA-pinned vendored plugin, and its hook command is a bare
 * `echo` of a deny decision — so a checker that merely pipes commands through it
 * certifies it as blocking `rm -rf /` and `cat ~/.ssh/id_rsa`. It does not: Claude
 * Code only ever invokes it for a force push. Refusing that false green IS the pitch.
 *
 * 🔴 THE COPY STANDARD FOR THIS SECTION AND ANY LIKE IT (Ernie, 2026-09-09).
 * A reader must look at the code and instantly think "wait — yeah, I have seen
 * this." Write the BUG they have already lived through, not the mechanism we
 * built. "A hook is a process, pipe it an event" describes plumbing; "the guard
 * you think protects you runs nothing" is the thing that happened to them.
 * Every beat should name a concrete failure a plugin author recognises: a guard
 * that looks unconditional and only ever fires on one command; a tool that is
 * silently dropped; a skill that never fires because a sibling took the prompt.
 * If a paragraph would still read fine in a competitor's docs, it is describing
 * a feature and has not earned its place — rewrite it as the failure.
 *
 * EVERY NUMBER IS PINNED. The rows and the 44/44 come from
 * __fixtures__/davila7-guard.json, regenerated by scripts/gen-davila7-expected.mjs
 * in `pretest:browser` and asserted by Measure.browser.test.tsx — the same mechanism
 * as the disaster battery, for the same reason: a retyped number is one that drifts,
 * and this section's whole claim is that it does not need a footnote.
 */

/**
 * The snippet is a REAL FILE the type-checker compiles (`npm run check` runs
 * `tsc --noEmit -p site/tsconfig.json`), imported here as text. A hand-typed string
 * is not checked by anything: the eval snippet shipped naming two exports that do
 * not exist — `defineEval` and `skillResolved` from "vigiles/eval" — with build,
 * lint, prettier, browser and e2e all green. Now a renamed export fails the build
 * with "Did you mean 'runHook'?" instead of reaching a reader.
 *
 * MEASURED LIMIT, so nobody over-trusts this: tsc catches the wrong NAME, and
 * catches wrong types only where the API is precisely typed. `tool: 123` currently
 * passes, because runHook's options type is loose there.
 */

function Verdict({ row }: { row: (typeof fixture.rows)[number] }) {
  return (
    <div className="flex flex-col gap-1 border-t border-border/60 py-4 sm:flex-row sm:items-baseline sm:justify-between sm:gap-6">
      <code className="whitespace-pre-wrap break-words font-mono text-sm text-foreground">
        {row.command}
      </code>
      <span
        className={`shrink-0 font-mono text-xs ${
          row.blocked ? "text-good" : "text-muted-foreground"
        }`}
      >
        {row.blocked ? "blocked" : "not run"}
      </span>
    </div>
  );
}

export function Measure() {
  const { rows, spellings } = fixture;
  return (
    <>
      <section className="border-t border-border/60">
        <div className="mx-auto w-full max-w-4xl px-6 py-20 sm:py-24">
          <p className="font-mono text-xs text-primary">
            $ vigiles test · no model · free in CI
          </p>
          <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
            Read it. Then run it.
          </h2>
          <p className="mt-4 max-w-2xl text-lg leading-relaxed text-muted-foreground">
            The repo above ships a force-push guard. Here is what it actually
            decided when we fed it real destructive commands.
          </p>

          <div className="mt-8">
            {rows.map((r) => (
              <Verdict key={r.id} row={r} />
            ))}
          </div>

          <p className="mt-6 max-w-2xl text-sm leading-relaxed text-muted-foreground">
            Its hook command is a bare <code className="font-mono">echo</code>{" "}
            of a deny decision, so a checker that just pipes commands through it
            would certify it as stopping all three. It does not — Claude Code
            only ever invokes it for a force push. vigiles reports what the
            guard was actually asked, and refuses the false green.
          </p>
          <p className="mt-4 max-w-2xl text-sm leading-relaxed text-muted-foreground">
            And it does not manufacture a complaint either: fed{" "}
            <strong className="text-foreground">
              {spellings.fed} shell re-spellings
            </strong>{" "}
            of a force push — quoted flags,{" "}
            <code className="font-mono">sudo</code>, tabs, escapes — this guard
            blocked{" "}
            <strong className="text-foreground">all {spellings.blocked}</strong>
            .
          </p>

          <CodeBlock code={RUN_HOOK} language="tsx" className="mt-8" />
          <p className="mt-3 text-sm text-muted-foreground">
            A hook is a process: an event on stdin, exit 2 to block. No agent
            binary, no API key, milliseconds.
          </p>
        </div>
      </section>

      <section className="border-t border-border/60">
        <div className="mx-auto w-full max-w-4xl px-6 py-20 sm:py-24">
          <p className="font-mono text-xs text-primary">
            $ vigiles eval · real model · your Claude subscription
          </p>
          <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
            Does the skill actually help?
          </h2>
          <p className="mt-4 max-w-2xl text-lg leading-relaxed text-muted-foreground">
            Whether a description makes a skill fire, and whether its guidance
            moves the agent at all, cannot be read off the file. It needs a
            model to choose — so you measure it.
          </p>

          <div className="mt-8 grid gap-px overflow-hidden rounded-xl border border-border/60 bg-border/60 sm:grid-cols-2">
            <div className="bg-card/40 p-6">
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">
                Claimed
              </p>
              <p className="mt-2 text-2xl font-bold text-muted-foreground">
                −65% tokens
              </p>
              <p className="mt-1 text-sm text-muted-foreground">
                an unverified number in a README
              </p>
            </div>
            <div className="bg-card/40 p-6">
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">
                Measured
              </p>
              <p className="mt-2 text-2xl font-bold text-foreground">−6%</p>
              <p className="mt-1 text-sm text-muted-foreground">
                the real number, on your own model
              </p>
            </div>
          </div>

          <p className="mt-6 max-w-2xl text-sm leading-relaxed text-muted-foreground">
            Runs on the Claude subscription you already pay for, not a metered
            API key — which is why measuring a harness is affordable at all.{" "}
            <a
              className="text-primary hover:underline"
              href="https://zernie.com/blog/token-savings-wrong-number/"
            >
              Read the measurement →
            </a>
          </p>
        </div>
      </section>
    </>
  );
}
