import { CodeBlock } from "@/components/CodeBlock";
import RUN_HOOK from "@/snippets/hook-test.ts?raw";
import fixture from "./__fixtures__/davila7-guard.json";
import lock from "./__fixtures__/tdd-trigger-rate.json";

/**
 * TEST and EVAL — the two beats `audit` cannot play.
 *
 * WHY IT EXISTS. The landing led with `audit` (a graded read) and named the other
 * three verbs once each in a map. A visitor came away thinking vigiles is a linter.
 * The founder, 2026-09-09: "audit is a starting point and then people going through
 * the website should think wow this stuff like testing and evals really solves my
 * problem."
 *
 * THE ARGUMENT, and why it is on THIS repo. The demo above grades
 * davila7/claude-code-templates. So these sections stay on the same repo the reader
 * just watched get graded, instead of introducing a hypothetical. Its force-push
 * guard is a real, MIT, SHA-pinned vendored plugin, and its hook command is a bare
 * `echo` of a deny decision — so a checker that merely pipes commands through it
 * certifies it as blocking `rm -rf /` and `cat ~/.ssh/id_rsa`. It does not: Claude
 * Code only ever invokes it for a force push. Refusing that false green IS the pitch.
 *
 * 🔴 THE COPY STANDARD FOR THIS SECTION AND ANY LIKE IT (Ernie, 2026-09-09).
 * A reader must look at the code and instantly think "wait — yeah, I have seen
 * this." Write the BUG they have already lived through, not the mechanism we
 * built. "A hook is a process, pipe it an event" describes plumbing; "the guard
 * you think protects you runs nothing" is the thing that happened to them.
 * Every beat should name a concrete failure a plugin author recognises: a guard
 * that looks unconditional and only ever fires on one command; a tool that is
 * silently dropped; a skill that never fires because a sibling took the prompt.
 * If a paragraph would still read fine in a competitor's docs, it is describing
 * a feature and has not earned its place — rewrite it as the failure.
 *
 * EVERY NUMBER IS PINNED. The rows and the 44/44 come from
 * __fixtures__/davila7-guard.json, regenerated by scripts/gen-davila7-expected.mjs
 * in `pretest:browser` and asserted by Measure.browser.test.tsx — the same mechanism
 * as the disaster battery, for the same reason: a retyped number is one that drifts,
 * and this section's whole claim is that it does not need a footnote.
 */

/**
 * The snippet is a REAL FILE the type-checker compiles (`npm run check` runs
 * `tsc --noEmit -p site/tsconfig.json`), imported here as text. A hand-typed string
 * is not checked by anything: the eval snippet shipped naming two exports that do
 * not exist — `defineEval` and `skillResolved` from "vigiles/eval" — with build,
 * lint, prettier, browser and e2e all green. Now a renamed export fails the build
 * with "Did you mean 'runHook'?" instead of reaching a reader.
 *
 * MEASURED LIMIT, so nobody over-trusts this: tsc catches the wrong NAME, and
 * catches wrong types only where the API is precisely typed. `tool: 123` currently
 * passes, because runHook's options type is loose there.
 */

function Verdict({ row }: { row: (typeof fixture.rows)[number] }) {
  return (
    <div className="flex flex-col gap-1 border-t border-border/60 py-4 sm:flex-row sm:items-baseline sm:justify-between sm:gap-6">
      <code className="whitespace-pre-wrap break-words font-mono text-sm text-foreground">
        {row.command}
      </code>
      <span
        className={`shrink-0 font-mono text-xs ${
          row.blocked ? "text-good" : "text-muted-foreground"
        }`}
      >
        {row.blocked ? "blocked" : "not run"}
      </span>
    </div>
  );
}

export function Measure() {
  const { rows, spellings } = fixture;
  // Only the prompts that did NOT reliably fire — the eight that always fire are
  // not the story, and listing all ten is the rule-dump shape we already cut once.
  const misses = lock.report.perPrompt.filter((p) => p.rate < 1);
  return (
    <>
      <section className="border-t border-border/60">
        <div className="mx-auto w-full max-w-4xl px-6 py-20 sm:py-24">
          <p className="font-mono text-xs text-primary">
            $ vigiles test · no model · free in CI
          </p>
          <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
            You have a safety hook. What does it actually stop?
          </h2>
          <p className="mt-4 max-w-2xl text-lg leading-relaxed text-muted-foreground">
            The repo above ships one. It looks like a blanket deny — and for two
            of these three commands, Claude Code never even calls it.
          </p>

          <div className="mt-8">
            {rows.map((r) => (
              <Verdict key={r.id} row={r} />
            ))}
          </div>

          <p className="mt-6 max-w-2xl text-sm leading-relaxed text-muted-foreground">
            Its hook command is a bare <code className="font-mono">echo</code>{" "}
            of a deny decision, so a checker that just pipes commands through it
            would certify it as stopping all three. It does not — Claude Code
            only ever invokes it for a force push. vigiles reports what the
            guard was actually asked, and refuses the false green.
          </p>
          <p className="mt-4 max-w-2xl text-sm leading-relaxed text-muted-foreground">
            And it does not manufacture a complaint either: fed{" "}
            <strong className="text-foreground">
              {spellings.fed} shell re-spellings
            </strong>{" "}
            of a force push — quoted flags,{" "}
            <code className="font-mono">sudo</code>, tabs, escapes — this guard
            blocked{" "}
            <strong className="text-foreground">all {spellings.blocked}</strong>
            .
          </p>

          <CodeBlock code={RUN_HOOK} language="tsx" className="mt-8" />
          <p className="mt-3 text-sm text-muted-foreground">
            The test lives next to the thing it tests —{" "}
            <code className="font-mono text-xs">hooks/block-force-push.sh</code>{" "}
            gets{" "}
            <code className="font-mono text-xs">
              hooks/block-force-push.harness.mjs
            </code>
            . One property earns that:{" "}
            <code className="font-mono text-xs">ls</code> answers &ldquo;is this
            tested?&rdquo; without running anything.
          </p>

          {/* Collapsed on purpose. A reader who has never had a test push to their
              real remote does not need this; the one who has, opens it. */}
          <details className="group mt-6 rounded-xl border border-border/60 bg-card/30 px-5">
            <summary className="cursor-pointer list-none py-4 text-base font-medium text-foreground">
              But my hook actually does things — what stops the test doing them
              for real?
            </summary>
            <div className="space-y-4 pb-5 text-sm leading-relaxed text-muted-foreground">
              <p className="text-foreground">
                You can throw away a temp directory. You cannot un-push a branch
                or un-charge an API call.
              </p>
              <p>
                <strong className="text-foreground">
                  Every run is disposable.
                </strong>{" "}
                Each test gets a fresh throwaway working directory, so a hook
                that writes files leaves nothing behind.
              </p>
              <p>
                <strong className="text-foreground">
                  Effects you cannot take back get intercepted, not contained.
                </strong>{" "}
                A tool call can be caught and asserted on without being allowed
                to happen — you check that the agent <em>tried</em> to push,
                while no push occurs.
              </p>
              <p>
                <strong className="text-foreground">
                  Somebody else&rsquo;s hook runs confined.
                </strong>{" "}
                Code you did not write executes with no network, a read-only
                filesystem and a cleared environment. That wall is Linux
                (bubblewrap); where the kernel features are absent vigiles
                refuses to run foreign code rather than quietly running it
                unconfined.
              </p>
            </div>
          </details>
        </div>
      </section>

      <section className="border-t border-border/60">
        <div className="mx-auto w-full max-w-4xl px-6 py-20 sm:py-24">
          <p className="font-mono text-xs text-primary">
            $ vigiles eval · real model · your Claude subscription
          </p>
          <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
            Your skill has a description. Does it fire?
          </h2>
          <p className="mt-4 max-w-2xl text-lg leading-relaxed text-muted-foreground">
            We measured a popular open-source TDD skill against ten ways of
            asking for test-first work. Eight reached it. These two did not:
          </p>

          <div className="mt-8 overflow-hidden rounded-xl border border-border/60">
            {misses.map((m) => (
              <div
                key={m.prompt}
                className="flex flex-col gap-1 border-b border-border/60 bg-card/40 p-5 sm:flex-row sm:items-baseline sm:justify-between sm:gap-6"
              >
                <p className="whitespace-pre-wrap break-words font-mono text-sm text-foreground">
                  {m.prompt}
                </p>
                <span className="shrink-0 font-mono text-xs text-muted-foreground">
                  fired {m.fired} of {m.trials}
                </span>
              </div>
            ))}
            <div className="bg-card/20 p-5">
              <p className="text-sm leading-relaxed text-muted-foreground">
                Every prompt it <em>did</em> fire on asks for something new.
                Both of these ask for tests around code that already exists —
                which is most of the work most people do.
              </p>
            </div>
          </div>

          <p className="mt-6 max-w-2xl text-sm leading-relaxed text-muted-foreground">
            {Math.round(lock.report.rate * 100)}% over {lock.report.n} runs (
            {lock.report.perPrompt.length} prompts x{" "}
            {lock.report.perPrompt[0].trials} trials, {lock.model}, measured{" "}
            {lock.builtAt.slice(0, 10)}). Run it against your own skill and you
            get the same shape of answer: which phrasings reach it, and which
            quietly do not. Billed to the Claude subscription you already pay
            for, not a metered key.
          </p>
        </div>
      </section>
    </>
  );
}
