import { existsSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { aliases } from "./vite.aliases";
import { ENGINE_VERSION } from "./vite.engine-version";

// Multi-page inputs: the landing (index.html) + one static page per audit check
// (checks/<slug>/index.html, generated by the `prebuild` step from src/checks/
// checks.ts). Listing them as rollup inputs makes each a real, indexable HTML file at
// a clean URL — no client router, no SSR. Enumerated with readdirSync (Node 20-safe —
// Pages CI runs Node 20; deliberately NOT fs.globSync, which is Node 22+) so adding a
// check needs no vite.config edit. Guarded by existsSync so `test:browser` (which
// doesn't run the generator) still resolves to just the landing.
const checksDir = fileURLToPath(new URL("checks", import.meta.url));
const checkPages = existsSync(checksDir)
  ? readdirSync(checksDir, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => `checks/${e.name}/index.html`)
  : [];
// The comparison page is a sibling static entry (site/comparison/index.html, written
// by the same prebuild generator). Guarded like checkPages so `test:browser`, which
// does not run the generator, still resolves to just the landing.
const comparisonPage = existsSync(
  fileURLToPath(new URL("comparison/index.html", import.meta.url)),
)
  ? ["comparison/index.html"]
  : [];
const inputs = Object.fromEntries(
  ["index.html", ...checkPages, ...comparisonPage].map((rel) => [
    rel.replace(/\/index\.html$/, "").replace(/\.html$/, "") || "index",
    fileURLToPath(new URL(rel, import.meta.url)),
  ]),
);

// Static multi-file build for GitHub Pages. `base: "./"` makes every asset
// reference relative, so the built site works whether it's served at the domain
// root (vigiles.sh) OR under a subpath (…github.io/vigiles/) — the Pages-routing
// decision is left open without hard-coding a base into the bundle.
export default defineConfig({
  base: "./",
  plugins: [react(), tailwindcss()],
  resolve: { alias: aliases },
  // The engine version namespaces the persistent grade-cache (site/src/demo/gradeCache.ts).
  define: { __ENGINE_V__: JSON.stringify(ENGINE_VERSION) },
  build: {
    outDir: "dist",
    rollupOptions: { input: inputs },
    commonjsOptions: {
      // The engine dist lives OUTSIDE the site root; let @rollup/plugin-commonjs
      // transform those `require()` graphs too (not just node_modules).
      include: [/dist\//, /node_modules/],
    },
  },
});
